### ISSUE TITLE
About similarity

### ISSUE THREAD

**Issue by hxnxn001** [chang2000/tfGMN#1]
Can this code be used to calculate the similarity of two graphs?
Is the Input G_1(V,E), G_2(V,E) and output the score of similarity?
Looking forward to your reply.

**Comment by tcalexwang** [comment]
According to the methods mentioned in the paper, a well labeled dataset is required to train the model to compute the similarity of two graphs.

So the answer is YES, but I suggest to write one from scratch since this one is kind of deprecated.
