### ISSUE TITLE
python&&TensorFlow version 

### ISSUE THREAD

**Issue by jams-xin** [chang2000/tfGMN#5]
您好，请问您能告知一下运行此代码所需的python，TensorFlow版本以及其他相关模块包版本吗？

**Comment by tcalexwang** [comment]
> 您好，请问您能告知一下运行此代码所需的python，TensorFlow版本以及其他相关模块包版本吗？

You can check out the latest requirement.txt.

**Comment by RZZBlackMagic** [comment]
@jams-xin hello, have you ever run this model?  Is there a public data set for this project? If not, Could you tell me the format of the data set?

Thanks
Best wishes
